### ISSUE TITLE
Fix non-compiling macros

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#594]
The following ROOT macros are currently not "compiling" (or ROOT fails loading them with .L). They should be fixed in order to reach a green state:

- [ ] /Detectors/EMCAL/testsimulation/drawEMCALgeometry.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckClusterShape.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckClusters.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckDigits.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckTracks.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C 
- [ ] /Detectors/Passive/macro/PutFrameInTop.C 
- [ ] /Detectors/TOF/prototyping/drawTOFgeometry.C 
- [ ] /Detectors/TOF/prototyping/test.C 
- [ ] /Detectors/TPC/monitor/macro/RunCompareMode3.C 
- [ ] /Detectors/TPC/monitor/macro/RunFindAdcError.C 
- [ ] /Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C 
- [ ] /Detectors/TPC/reconstruction/macro/RawClusterFinder.C 
- [ ] /Detectors/TPC/reconstruction/macro/convertClusters.C 
- [ ] /Detectors/TPC/reconstruction/macro/convertTracks.C 
- [ ] /Detectors/TPC/reconstruction/macro/dEdxRes.C 
- [ ] /Detectors/TPC/reconstruction/macro/runRawClusterFinder.C 
- [ ] /Detectors/TPC/reconstruction/macro/testClustererData.C 
- [ ] /Detectors/TPC/reconstruction/macro/testRawRead.C 
- [ ] /Detectors/TPC/reconstruction/macro/testTracks.C 
- [ ] /Detectors/TPC/simulation/macro/testHitsDigitsClusters.C 
- [ ] /Utilities/aliceHLTwrapper/macros/hltConfigurations.C 
- [ ] /Utilities/aliceHLTwrapper/macros/overlayClusters.C 
- [ ] /Utilities/aliceHLTwrapper/macros/runHLT.C 
- [ ] /macro/CheckClusters_mft.C 
- [ ] /macro/compare_cluster.C 
- [ ] /macro/putCondition.C 
- [ ] /macro/run_clus_its.C 
- [ ] /macro/run_clus_mft.C 
- [ ] /macro/run_digi.C 
- [ ] /macro/run_digi_its.C 
- [ ] /macro/run_digi_mft.C 
- [ ] /macro/run_reco_mft.C 
- [ ] /macro/run_sim_its.C 
- [ ] /macro/run_sim_its_ALP3.C 
- [ ] /macro/run_sim_mft.C 
- [ ]  /macro/run_trac_its.C

**Comment by ZdravkoD** [comment]
Fixed macros:

- [x]  /Detectors/EMCAL/testsimulation/drawEMCALgeometry.C
- [ ]  /Detectors/ITSMFT/ITS/macros/test/CheckClusterShape.C
- [ ]  /Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
- [ ]  /Detectors/ITSMFT/ITS/macros/test/CheckDigits.C
- [ ]  /Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- [ ]  /Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
- [ ]  /Detectors/Passive/macro/PutFrameInTop.C
- [ ]  /Detectors/TOF/prototyping/drawTOFgeometry.C
- [ ]  /Detectors/TOF/prototyping/test.C
- [ ]  /Detectors/TPC/monitor/macro/RunCompareMode3.C
- [ ]  /Detectors/TPC/monitor/macro/RunFindAdcError.C
- [ ]  /Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C
- [ ]  /Detectors/TPC/reconstruction/macro/RawClusterFinder.C
- [ ]  /Detectors/TPC/reconstruction/macro/convertClusters.C
- [ ]  /Detectors/TPC/reconstruction/macro/convertTracks.C
- [ ]  /Detectors/TPC/reconstruction/macro/dEdxRes.C
- [ ]  /Detectors/TPC/reconstruction/macro/runRawClusterFinder.C
- [ ]  /Detectors/TPC/reconstruction/macro/testClustererData.C
- [ ]  /Detectors/TPC/reconstruction/macro/testRawRead.C
- [ ]  /Detectors/TPC/reconstruction/macro/testTracks.C
- [ ]  /Detectors/TPC/simulation/macro/testHitsDigitsClusters.C
- [ ]  /Utilities/aliceHLTwrapper/macros/hltConfigurations.C
- [ ]  /Utilities/aliceHLTwrapper/macros/overlayClusters.C
- [ ]  /Utilities/aliceHLTwrapper/macros/runHLT.C
- [ ]  /macro/CheckClusters_mft.C
- [ ]  /macro/compare_cluster.C
- [ ]  /macro/putCondition.C
- [ ]  /macro/run_clus_its.C
- [ ]  /macro/run_clus_mft.C
- [ ]  /macro/run_digi.C
- [ ]  /macro/run_digi_its.C
- [ ]  /macro/run_digi_mft.C
- [ ]  /macro/run_reco_mft.C
- [ ]  /macro/run_sim_its.C
- [ ]  /macro/run_sim_its_ALP3.C
- [ ]  /macro/run_sim_mft.C
- [ ]  /macro/run_trac_its.C

**Comment by bovulpes** [comment]
Hi Sandro,

First, I have a problem in compiling the MFT macros if I add to

#if !defined(__CINT__) || defined(__MAKECINT__)

another definition check

#if (!defined(__CINT__) && !defined(__CLING__)) || defined(__MAKECINT__)

as you have corrected them, whereas only with the first checks it compiles and runs fine.

I understand that we can put macros in Detectors/ITSMFT/MFT/macros for instance, without being checked for compilation and installed. Is it recommended to have some minimal macros also at root in the "macro" directory to be checked and installed?

**Comment by shahor02** [comment]
I had the same problem: the correct protection is (https://root.cern.ch/root/htmldoc/guides/users-guide/Cling.html#moving-between-interpreter-and-compiler):
````
#if !defined(__CLING__) || defined(__ROOTCLING__)
#include ...
#endif
````
I don't see why do we need __CINT__ and __MAKECINT__ protections, in any case our code will not run on root5.

I'll open PR with the fix.

**Comment by bovulpes** [comment]
I still have a problem with the MFT macros when I try to simply load and compile in root, I always need to load the necessary MFT libraries, while for the ITS is is not necessary: for example run_sim_its.C and run_sim_mft.C
.L run_sim_its.C+    is ok
.L run_sim_mft.C+   has undefined reference to the MFT libraries
Is there a hidden rootlogon somewhere which should be modified?

**Comment by shahor02** [comment]
@bovulpes : I am sure there is no any special rootlogon for ITS, the libraries are supposed to be loaded automatically. The libITSSimulation.rootmap and libMFTSimulation.rootmap look similar, no idea why it is not loaded for MFT. Perhaps @ktf may suggest something?
